// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Host preferences and drafts are separate from scientific Operations.
 */
export type ApplicationState = { key: string, version: string | null, value: JsonValue, };
