// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CallerKind } from "./CallerKind";

export type CallerIdentity = { kind: CallerKind, id: string, };
