// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationRecord } from "./OperationRecord";

export type CancellationRequestOutcome = {
/**
 * Acceptance of the request is not confirmation that native work stopped.
 */
accepted: boolean, operation: OperationRecord, };
