// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CapabilityKind } from "./CapabilityKind";
import type { CapabilityRef } from "./CapabilityRef";
import type { NextRead } from "./NextRead";

export type CapabilitySummary = { capability: CapabilityRef, kind: CapabilityKind, module: string, summary: string, describe: NextRead, };
