// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type CapabilityExample = {
/**
 * Domain arguments. Operation callers also supply their own request ID.
 */
arguments: JsonValue, result_explanation: string, };
