// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CapabilityExample } from "./CapabilityExample";
import type { CapabilityPrecondition } from "./CapabilityPrecondition";
import type { CapabilityRef } from "./CapabilityRef";

export type CapabilityDocumentation = { summary: string, purpose: string, when_to_use: Array<string>, limitations: Array<string>, owner: string, effects: string, retry_rule: string, cancellation_rule: string, preconditions: Array<CapabilityPrecondition>, examples: Array<CapabilityExample>, related_capabilities: Array<CapabilityRef>, related_skills: Array<string>, position_units: Array<string>, };
