// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CapabilityRef } from "./CapabilityRef";

export type CapabilityPrecondition = { parameter: string, requirement: string, read_from: CapabilityRef | null, };
