// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CapabilityRef } from "./CapabilityRef";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Ephemeral owner control. Arguments may contain secrets and never become an
 * Operation, receipt, event or diagnostic payload.
 */
export type ControlRequest = { capability: CapabilityRef, arguments: JsonValue, };
