// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CapabilityRef } from "./CapabilityRef";
import type { ContractFailureKind } from "./ContractFailureKind";
import type { OwnerContractViolation } from "./OwnerContractViolation";
import type { UncommittedCandidate } from "./UncommittedCandidate";

export type ContractFailureRecovery = { kind: ContractFailureKind, capability: CapabilityRef, automatic_reexecution: boolean, execution_started: boolean, violations: Array<OwnerContractViolation>,
/**
 * Original uncommitted values. These are unvalidated evidence, not domain facts.
 */
candidate: UncommittedCandidate, };
