// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DiagnosticContinuation = "read_again" | "refresh_observation" | "inspect_original" | "correct_input" | "none";
