// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiagnosticCode } from "./DiagnosticCode";
import type { DiagnosticContinuation } from "./DiagnosticContinuation";
import type { NextRead } from "./NextRead";

export type Diagnostic = { code: DiagnosticCode, message: string, continuation: DiagnosticContinuation, next_reads: Array<NextRead>, };
