// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DiagnosticCode = "busy" | "stale_session" | "observation_expired" | "content_changed" | "budget_exceeded" | "unavailable" | "invalid_input" | "access_denied" | "idempotency_conflict" | "not_found" | "execution_failed" | "cancelled" | "outcome_uncertain" | "contract_violation";
