// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EffectHint = "commits_operation" | "plugin_defined" | "needs_network" | "may_write_project" | "may_mutate_runtime" | "may_spawn_process" | "uses_secret" | "produces_artifact";
