// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CapabilitySummary } from "./CapabilitySummary";

export type HostCatalog = { entries: Array<CapabilitySummary>, total: number, next_cursor: string | null, utf8_bytes: number, limit_reason: string | null, };
