// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HostCatalogArguments = { module: string | null, keyword: string | null, cursor: string | null, limit: number, };
