// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AfterStartRecoveryAction } from "./AfterStartRecoveryAction";
import type { BeforeStartRecoveryAction } from "./BeforeStartRecoveryAction";

export type HostRestartRecovery = { "previous_status": "accepted", action: BeforeStartRecoveryAction, } | { "previous_status": "running", action: AfterStartRecoveryAction, } | { "previous_status": "reconciling", action: AfterStartRecoveryAction, };
