// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CapabilityRef } from "./CapabilityRef";

export type HostDescribeArguments = { capability: CapabilityRef | null, module: string | null, };
