// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CapabilityDescriptor } from "./CapabilityDescriptor";
import type { CapabilitySummary } from "./CapabilitySummary";
import type { ModuleAvailability } from "./ModuleAvailability";

export type HostDescription = { "kind": "capability", descriptor: CapabilityDescriptor, } | { "kind": "module", module: ModuleAvailability, capabilities: Array<CapabilitySummary>, };
