// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ControlRequest } from "./ControlRequest";
import type { InvokeRequest } from "./InvokeRequest";
import type { OperationId } from "./OperationId";
import type { QueryRequest } from "./QueryRequest";
import type { ReconcileOperationCommit } from "./ReconcileOperationCommit";

/**
 * The local session edge forwards these five ports to the Host.
 */
export type HostRequest = { "method": "control", "params": ControlRequest } | { "method": "invoke", "params": InvokeRequest } | { "method": "get_operation", "params": { operation_id: OperationId, } } | { "method": "request_cancellation", "params": { operation_id: OperationId, only_if_pending?: boolean, } } | { "method": "reconcile_commit", "params": ReconcileOperationCommit } | { "method": "query_snapshot", "params": QueryRequest } | { "method": "subscribe", "params": { after_sequence: number, limit: number, } };
