// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModuleAvailability } from "./ModuleAvailability";
import type { OverviewObservation } from "./OverviewObservation";
import type { TargetRef } from "./TargetRef";

export type HostOverview = { project_root: string | null, targets: Array<TargetRef>, modules: Array<ModuleAvailability>,
/**
 * Each component retains its own source, time and completeness.
 */
observations: Array<OverviewObservation>, atomic_snapshot: boolean, };
