// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type McpSessionObservation = {
/**
 * A local display reference, never the MCP transport credential/session ID.
 */
connection_id: string, client_reported_name: string | null, client_reported_version: string | null, initialized_at_ms: number, last_request_at_ms: number, closed_at_ms: number | null,
/**
 * Successful bounded response prepared for this client, not a delivery or
 * model-consumption acknowledgement and not scientific verification.
 */
overview_served_at_ms: number | null, };
