// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NextRead } from "./NextRead";

export type ModuleAvailability = { module: string, available: boolean, reasons: Array<string>, catalog: NextRead, };
