// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CapabilityRef } from "./CapabilityRef";
import type { JsonValue } from "./serde_json/JsonValue";

export type NextRead = { purpose: string, capability: CapabilityRef, arguments: JsonValue, missing_identity_fields: Array<string>, };
