// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ObservationCompleteness } from "./ObservationCompleteness";
import type { QueryStatus } from "./QueryStatus";

export type Observed<T> = { source: string, observed_at_ms: number, status: QueryStatus, completeness: ObservationCompleteness, data: T | null, notices: Array<string>, };
