// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationRecord } from "./OperationRecord";
import type { RecordedOperationContract } from "./RecordedOperationContract";

export type OperationGetResult = {
/**
 * Output/recovery are polymorphic according to this record's exact capability.
 */
record: OperationRecord | null, output_contract: RecordedOperationContract | null, };
