// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationCommitPhase } from "./OperationCommitPhase";
import type { OperationCommitReference } from "./OperationCommitReference";
import type { OperationId } from "./OperationId";
import type { OperationStatus } from "./OperationStatus";

export type OperationCommitStatus = { operation_id: OperationId, operation_status: OperationStatus, phase: OperationCommitPhase, reference: OperationCommitReference | null, };
