// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Diagnostic } from "./Diagnostic";
import type { NextRead } from "./NextRead";
import type { Operation } from "./Operation";
import type { OperationOutcome } from "./OperationOutcome";
import type { OperationStatus } from "./OperationStatus";
import type { JsonValue } from "./serde_json/JsonValue";

export type OperationRecord = { operation: Operation, status: OperationStatus, outcome: OperationOutcome | null, output: JsonValue | null, error: string | null, recovery: JsonValue | null, cancellation_requested: boolean, updated_at_ms: number,
/**
 * Read-only navigation derived from this record and visible registered capabilities.
 */
next_reads?: Array<NextRead>, diagnostics?: Array<Diagnostic>, };
