// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationEvidenceReference } from "./OperationEvidenceReference";

export type OperationEvidencePage = { reference: OperationEvidenceReference, offset: number,
/**
 * Exact original JSON bytes. Reassemble before UTF-8 decoding or parsing.
 */
bytes: Array<number>, next_offset: number | null, };
