// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationEvidenceReference } from "./OperationEvidenceReference";

export type OperationReadEvidenceArguments = { reference: OperationEvidenceReference,
/**
 * Zero-based byte offset in the original UTF-8 JSON evidence document.
 */
offset: number, limit_bytes: number, };
