// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An event position within the visible journal, not a scientific state version.
 */
export type OperationEventsCheckpoint = { sequence: number, };
