// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OutboxRecord } from "./OutboxRecord";

export type OperationEventsPage = { events: Array<OutboxRecord>, after_sequence: number,
/**
 * Cursor immediately after the last returned event; unchanged on an empty page.
 */
next_after_sequence: number,
/**
 * More visible events were observed while reading this page. New events may arrive later.
 */
has_more: boolean, limit_reason: string | null, };
