// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationEvidenceKind } from "./OperationEvidenceKind";
import type { OperationId } from "./OperationId";

export type OperationEvidenceReference = { operation_id: OperationId, kind: OperationEvidenceKind, sha256: string, byte_size: number, };
