// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CallerIdentity } from "./CallerIdentity";
import type { CapabilityRef } from "./CapabilityRef";
import type { EffectHint } from "./EffectHint";
import type { OperationAdmission } from "./OperationAdmission";
import type { OperationId } from "./OperationId";
import type { Precondition } from "./Precondition";
import type { TargetRef } from "./TargetRef";
import type { JsonValue } from "./serde_json/JsonValue";

export type Operation = { operation_id: OperationId, client_request_id: string, caller: CallerIdentity, principal?: CallerIdentity, capability: CapabilityRef, domain: string, target: TargetRef, normalized_arguments: JsonValue, invocation_digest: string, idempotency_scope?: string, preconditions: Array<Precondition>, potential_effects: Array<EffectHint>, correlation_id: string, causation_id: OperationId | null, trace_parent: string | null, accepted_at_ms: number,
/**
 * Captured by Operation admission, never accepted from a plugin result.
 */
admission?: OperationAdmission, };
