// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CapabilityDescriptor } from "./CapabilityDescriptor";
import type { JsonValue } from "./serde_json/JsonValue";

export type OperationAdmission = {
/**
 * Canonical original request before owner preparation/normalization.
 */
request_digest: string,
/**
 * Exact contract retained after dynamic contribution removal or replacement.
 */
descriptor: CapabilityDescriptor,
/**
 * Validated owner qualification, captured separately from user arguments.
 */
owner_context: JsonValue, };
