// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationId } from "./OperationId";

/**
 * Digest of the exact, validated result retained by the original journal.
 * The reference is an identity check; callers never supply a replacement plan.
 */
export type OperationCommitReference = { operation_id: OperationId, sha256: string, byte_size: number, };
