// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationId } from "./OperationId";
import type { JsonValue } from "./serde_json/JsonValue";

export type OutboxRecord = { sequence: number, message_id: string, operation_id: OperationId, topic: string, payload: JsonValue, created_at_ms: number, delivered_at_ms: number | null, };
