// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Diagnostic } from "./Diagnostic";
import type { NextRead } from "./NextRead";
import type { ObservationCompleteness } from "./ObservationCompleteness";
import type { QueryStatus } from "./QueryStatus";
import type { TargetRef } from "./TargetRef";
import type { JsonValue } from "./serde_json/JsonValue";

export type QuerySnapshot = { target: TargetRef, source: string, observed_at_ms: number, status: QueryStatus, completeness: ObservationCompleteness, data: JsonValue | null, notices: Array<string>, next_reads: Array<NextRead>, diagnostics: Array<Diagnostic>, };
