// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Diagnostic } from "./Diagnostic";
import type { NextRead } from "./NextRead";
import type { ObservationCompleteness } from "./ObservationCompleteness";
import type { QueryStatus } from "./QueryStatus";
import type { TargetRef } from "./TargetRef";
import type { JsonValue } from "./serde_json/JsonValue";

export type QuerySnapshot = { target: TargetRef, source: string,
/**
 * Source-reported Unix milliseconds for this observation. Null means the
 * time is unknown; receiving a reply does not establish a fresh observation.
 */
observed_at_ms: number | null, status: QueryStatus, completeness: ObservationCompleteness, data: JsonValue | null, notices: Array<string>, next_reads: Array<NextRead>, diagnostics: Array<Diagnostic>, };
