// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationSummary } from "./OperationSummary";

export type RecentOperations = { operations: Array<OperationSummary>, next_cursor: number | null, };
