// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationId } from "./OperationId";

export type RecentOperationsArguments = { before_cursor: number | null, client_request_id: string | null, operation_id: OperationId | null, limit: number, };
