// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CapabilityRef } from "./CapabilityRef";
import type { NextRead } from "./NextRead";
import type { RecordedContractAvailability } from "./RecordedContractAvailability";

export type RecordedOperationContract = { capability: CapabilityRef, availability: RecordedContractAvailability, describe: NextRead | null, };
