// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RecordedContractAvailability = "registered" | "owner_unavailable_in_this_host";
