// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Changes hosting configuration, not a scientific capability or an Agent plan.
 */
export type SelectProject = { project_root: string, };
