// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HostRequest } from "./HostRequest";
import type { TestProjectId } from "./TestProjectId";

export type SessionFrame = { id: string,
/**
 * Select an existing test Host owned by the parent project. Omission selects
 * the parent; an unavailable explicit selection never falls back to it.
 */
test_project?: TestProjectId, request: HostRequest, };
