// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationOutcome } from "./OperationOutcome";
import type { UncommittedEffectObservation } from "./UncommittedEffectObservation";
import type { UncommittedEvent } from "./UncommittedEvent";
import type { UncommittedFact } from "./UncommittedFact";
import type { JsonValue } from "./serde_json/JsonValue";

export type UncommittedOwnerResult = { outcome: OperationOutcome,
/**
 * Exact original owner output, which failed its recorded capability contract.
 */
output: JsonValue | null, error: string | null,
/**
 * Exact original recovery material, retained even when malformed.
 */
recovery: JsonValue | null, facts: Array<UncommittedFact>, effect_observations: Array<UncommittedEffectObservation>, events: Array<UncommittedEvent>, };
