// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ObservationCompleteness } from "./ObservationCompleteness";
import type { JsonValue } from "./serde_json/JsonValue";

export type UncommittedEffectObservation = { kind: string, source: string,
/**
 * Unvalidated original owner observation, retained solely for investigation.
 */
detail: JsonValue, observed_at_ms: number, completeness: ObservationCompleteness, };
