// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type UncommittedEvent = { kind: string,
/**
 * Unvalidated original event; it has not been published to the scientific outbox.
 */
payload: JsonValue, };
