// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type UncommittedFact = { domain: string, schema: string, key: string,
/**
 * Unvalidated original fact payload; this recovery document does not commit it.
 */
value: JsonValue, };
