// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationEvidenceReference } from "./OperationEvidenceReference";
import type { UncommittedOwnerResult } from "./UncommittedOwnerResult";

export type UncommittedCandidate = { "kind": "inline", result: UncommittedOwnerResult, } | { "kind": "evidence", reference: OperationEvidenceReference, };
