[package]
name = "rho-sqlite"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[features]
# Generic UI state can be omitted for journal-only users.
default = ["application-store"]
application-store = []

[dependencies]
uuid.workspace = true
async-trait.workspace = true
rho-contract = { path = "../../contract" }
rho-operation = { path = "../../operation" }
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
tempfile.workspace = true
tokio.workspace = true
