// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactId } from "./ArtifactId.js";
import type { CapabilityKey } from "./CapabilityKey.js";
import type { InstanceAlias } from "./InstanceAlias.js";
import type { RevisionId } from "./RevisionId.js";
import type { JsonValue } from "./serde_json/JsonValue.js";

export type ActivatePlugin = { revision: RevisionId, artifact: ArtifactId, target: string, alias: InstanceAlias, configuration: JsonValue,
/**
 * Exact optional declarations selected for this activation, never inferred
 * from configuration, package availability or an eventual view request.
 */
optional_capabilities?: Array<CapabilityKey>, };
