// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstanceAlias } from "./InstanceAlias.js";
import type { InstanceRef } from "./InstanceRef.js";
import type { ScenarioRevisionId } from "./ScenarioRevisionId.js";
import type { ViewInstanceId } from "./ViewInstanceId.js";
import type { WindowId } from "./WindowId.js";

/**
 * Exact, already prepared instances and views. Preparation uses ordinary
 * activation/view ports; applying changes presentation and routing only.
 */
export type ApplyScenario = { window: WindowId, revision: ScenarioRevisionId, expected_layout_version: number, instances: { [key in InstanceAlias]: InstanceRef },
/**
 * Definition view id to an existing live view in this exact window. Reused
 * views retain their current state and unsynchronized document contents.
 */
views: { [key in ViewInstanceId]: ViewInstanceId }, };
