// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Host-issued native paths, separate from user configuration. The project is
 * normalized by the Host; data belongs to this exact instance and is retained
 * after release. These paths are not a sandbox or a general Host credential.
 */
export type BackendEnvironment = { project_root: string, data_root: string, };
