// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackagePath } from "./PackagePath.js";

export type BackendEntrypoint = { executable: PackagePath, arguments: Array<string>, };
