// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BuildRecipe = {
/**
 * Executable and literal arguments, without a shell interpolation layer.
 */
command: Array<string>, };
