// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactId } from "./ArtifactId.js";
import type { PackageFile } from "./PackageFile.js";
import type { PackagePath } from "./PackagePath.js";
import type { RevisionId } from "./RevisionId.js";

export type BuildArtifact = { id: ArtifactId, revision: RevisionId,
/**
 * Examples: ui-web, aarch64-apple-darwin. No platform is selected implicitly.
 */
target: string, files: { [key in PackagePath]: PackageFile }, };
