// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CancellationSupport } from "./CancellationSupport.js";
import type { CapabilityKey } from "./CapabilityKey.js";
import type { CapabilityKind } from "./CapabilityKind.js";
import type { JsonValue } from "./serde_json/JsonValue.js";

export type CapabilityContribution = { capability: CapabilityKey, kind: CapabilityKind, title: string, description: string, input_schema: JsonValue,
/**
 * Valid scientific arguments used in discovery; the Host adds provider binding.
 */
examples: Array<JsonValue>, output_schema: JsonValue, recovery_schema: JsonValue, required_scopes: Array<string>, effects: Array<string>, cancellation: CancellationSupport,
/**
 * Optional read-only owner preflight, invoked before Operation admission.
 */
preflight: CapabilityKey | null, };
