// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CapabilityKey } from "./CapabilityKey.js";

export type CapabilityRequirement = { capability: CapabilityKey, scopes: Array<string>, };
