// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BranchId } from "./BranchId.js";
import type { PackagePath } from "./PackagePath.js";
import type { PluginSourceEdit } from "./PluginSourceEdit.js";
import type { RevisionId } from "./RevisionId.js";

export type CheckpointPlugin = { branch: BranchId, expected_head: RevisionId,
/**
 * At most 128 edits and 128 KiB of decoded inline content per checkpoint.
 * Manifest file declarations must describe the complete resulting source tree.
 */
changes: { [key in PackagePath]: PluginSourceEdit }, };
