// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginViewCloseMode } from "./PluginViewCloseMode.js";
import type { ViewInstanceId } from "./ViewInstanceId.js";

export type ClosePluginView = { view: ViewInstanceId, mode: PluginViewCloseMode, };
