// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RevisionId } from "./RevisionId.js";

export type ComparePluginRevisions = { before: RevisionId, after: RevisionId, };
