// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContributionId } from "./ContributionId.js";
import type { InstanceRef } from "./InstanceRef.js";
import type { WindowId } from "./WindowId.js";
import type { JsonValue } from "./serde_json/JsonValue.js";

export type ContextReference = { provider: InstanceRef, contribution: ContributionId, window: WindowId,
/**
 * Owner-defined identity and observed native version/digest. Preview must
 * revalidate these against the original source; never silently refresh them.
 */
selector: JsonValue, };
