// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContextItem } from "./ContextItem.js";
import type { ResourceReference } from "./ResourceReference.js";
import type { JsonValue } from "./serde_json/JsonValue.js";

export type ContextPreview = { item: ContextItem,
/**
 * Plain text, never executable markup. Truncation must end at a UTF-8 boundary.
 */
text: string, truncated: boolean,
/**
 * Owner-defined bounded presentation data. Large artifacts use resources.
 */
data: JsonValue, resources: Array<ResourceReference>, };
