// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue.js";

export type ContextSearch = {
/**
 * Empty text lists available sources. Owners document which fields match.
 */
text: string,
/**
 * Opaque owner cursor; continuation does not imply a frozen multi-page read.
 */
after: JsonValue | null, limit: number, };
