// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContributionId } from "./ContributionId.js";
import type { InstanceRef } from "./InstanceRef.js";
import type { JsonValue } from "./serde_json/JsonValue.js";

export type ContextReference = { provider: InstanceRef, contribution: ContributionId,
/**
 * Owner-defined identity and observed native version/digest. Preview must
 * revalidate these against the original source; never silently refresh them.
 * Project, caller and authority come from the trusted call context; a view
 * caller's window restriction is held by the Host, never by this value.
 */
selector: JsonValue, };
