// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContextReference } from "./ContextReference.js";

export type ContextItem = { reference: ContextReference, title: string, description: string,
/**
 * A presentation hint supplied by the owner, not a closed core view enum.
 */
kind: string, };
