// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContextItem } from "./ContextItem.js";
import type { JsonValue } from "./serde_json/JsonValue.js";

export type ContextPage = { items: Array<ContextItem>, next: JsonValue | null,
/**
 * Explain partial, cached or unavailable observations without concealing
 * them as empty results. Completeness also belongs in the query envelope.
 */
notices: Array<string>, };
