// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CapabilityKey } from "./CapabilityKey.js";
import type { ContributionId } from "./ContributionId.js";

export type ContextContribution = { id: ContributionId, title: string, search: CapabilityKey, preview: CapabilityKey, };
