// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstanceAlias } from "./InstanceAlias.js";
import type { ScenarioInstance } from "./ScenarioInstance.js";

/**
 * An explicit backend test gets a fresh native project and journal. No existing
 * project path, session, provider binding or launch credential is accepted.
 */
export type CreatePluginTestProject = { name: string, instances: { [key in InstanceAlias]: ScenarioInstance }, };
