// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackagePath } from "./PackagePath.js";
import type { JsonValue } from "./serde_json/JsonValue.js";

export type CustomComponent = { source: PackagePath, export: string, properties_schema: JsonValue, input_schema: JsonValue, output_schema: JsonValue, };
