// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContributionId } from "./ContributionId.js";

export type DataBinding = { source: ContributionId,
/**
 * Property path, interpreted without eval or executable expressions.
 */
path: Array<string>, };
