// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DraftId } from "./DraftId.js";
import type { DraftSource } from "./DraftSource.js";
import type { WindowId } from "./WindowId.js";

export type DiscardDocumentDraft = { window: WindowId, draft: DraftId, source: DraftSource, expected_version: number, };
