// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentDigest } from "./ContentDigest.js";
import type { DraftId } from "./DraftId.js";
import type { DraftSource } from "./DraftSource.js";
import type { JsonValue } from "./serde_json/JsonValue.js";

/**
 * Opaque synchronized metadata; content is read separately at this version.
 */
export type DocumentDraftSummary = { draft: DraftId, source: DraftSource, version: number, digest: ContentDigest, bytes: number, metadata: JsonValue, };
