// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DocumentDraftSummary } from "./DocumentDraftSummary.js";
import type { DraftId } from "./DraftId.js";

export type DocumentDraftPage = { drafts: Array<DocumentDraftSummary>, next: DraftId | null, };
