// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentDigest } from "./ContentDigest.js";
import type { DraftId } from "./DraftId.js";

export type DocumentDraftChunk = { draft: DraftId, version: number, digest: ContentDigest, offset: number, base64: string, next: number | null, };
