// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DraftContent } from "./DraftContent.js";
import type { DraftId } from "./DraftId.js";
import type { DraftSource } from "./DraftSource.js";
import type { PrincipalId } from "./PrincipalId.js";
import type { ProjectId } from "./ProjectId.js";
import type { WindowId } from "./WindowId.js";
import type { JsonValue } from "./serde_json/JsonValue.js";

export type DocumentDraft = { draft: DraftId, project: ProjectId, principal: PrincipalId, window: WindowId, source: DraftSource,
/**
 * One draft's compare-and-swap version, never a scientific revision.
 */
version: number, content: DraftContent, metadata: JsonValue,
/**
 * Explicit discard releases content and its source revision. The tombstone
 * prevents a delayed first save from recreating the discarded identity.
 */
discarded: boolean, };
