// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentDigest } from "./ContentDigest.js";
import type { DraftChunkReference } from "./DraftChunkReference.js";

export type DraftContent = { digest: ContentDigest, bytes: number,
/**
 * Canonical 64 KiB chunks, except for the final chunk. Empty content has
 * no chunks. Full content and every chunk are verified before publication.
 */
chunks: Array<DraftChunkReference>, };
