// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactId } from "./ArtifactId.js";
import type { RevisionId } from "./RevisionId.js";

export type ExportPluginArchive = { revision: RevisionId,
/**
 * Exact artifact identities, sorted and unique. Empty exports source only.
 */
artifacts: Array<ArtifactId>, };
