// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CapabilityKey } from "./CapabilityKey.js";
import type { CapabilityKind } from "./CapabilityKind.js";
import type { ProjectId } from "./ProjectId.js";
import type { JsonValue } from "./serde_json/JsonValue.js";

/**
 * The exact current startup contract in this project. Dynamic contributions
 * cannot acquire a Host identity by using this query. Reading a write contract
 * does not grant its scopes or invoke it.
 */
export type HostCapabilityContract = { project: ProjectId, capability: CapabilityKey, kind: CapabilityKind, description: string, input_schema: JsonValue, required_scopes: Array<string>, };
