// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactId } from "./ArtifactId.js";
import type { PluginId } from "./PluginId.js";
import type { PluginInstanceId } from "./PluginInstanceId.js";
import type { RevisionId } from "./RevisionId.js";

export type InstanceRef = { instance: PluginInstanceId, plugin: PluginId, revision: RevisionId, artifact: ArtifactId, };
