// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DraftId } from "./DraftId.js";
import type { DraftSource } from "./DraftSource.js";
import type { WindowId } from "./WindowId.js";

/**
 * Enumerate retained, non-discarded drafts in one explicit window. Each page
 * is a current observation, not an immutable snapshot across subsequent reads.
 */
export type ListDocumentDrafts = { window: WindowId, source: DraftSource | null,
/**
 * Exclusive identity cursor, independent of the cursor draft's existence.
 */
after: DraftId | null, limit: number, };
