// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BranchId } from "./BranchId.js";
import type { PluginId } from "./PluginId.js";

export type ListPluginBranches = { plugin: PluginId, after: BranchId | null, limit: number, };
