// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContributionId } from "./ContributionId.js";
import type { InstanceRef } from "./InstanceRef.js";
import type { ResourceReference } from "./ResourceReference.js";
import type { WindowId } from "./WindowId.js";
import type { JsonValue } from "./serde_json/JsonValue.js";

export type OpenPluginView = { instance: InstanceRef, contribution: ContributionId, window: WindowId, configuration: JsonValue,
/**
 * Immutable resource context; it confers no resource-read authority.
 */
resource?: ResourceReference, };
