// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeId } from "./NodeId.js";
import type { OpenPluginView } from "./OpenPluginView.js";

/**
 * Create an exact view and select it in one window's presentation atomically.
 */
export type OpenPluginWindowView = { view: OpenPluginView, expected_layout_version: number,
/**
 * Existing tab group. None creates a group only in an entirely empty window.
 */
group: NodeId | null, };
