// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginViewRecord } from "./PluginViewRecord.js";
import type { PluginWindowLayout } from "./PluginWindowLayout.js";

export type OpenedPluginWindowView = { view: PluginViewRecord, layout: PluginWindowLayout, };
