// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationId } from "./OperationId.js";
import type { PluginOutcome } from "./PluginOutcome.js";
import type { ProviderBinding } from "./ProviderBinding.js";

/**
 * Host-to-owner notification derived only from the original terminal journal
 * record. This releases native scheduling fences; it is not another operation,
 * a commit plan, a cancellation request or a caller-supplied control.
 */
export type OperationSettlement = { operation_id: OperationId, binding: ProviderBinding, outcome: PluginOutcome, };
