// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OutputCapture = { bytes: Array<number>, total_bytes: number, truncated: boolean, eof: boolean, };
