// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentDigest } from "./ContentDigest.js";

export type PackageFile = { digest: ContentDigest, bytes: number, executable: boolean, };
