// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationId } from "./OperationId.js";
import type { ProviderBinding } from "./ProviderBinding.js";

/**
 * A Host-only fence on an original invocation, never a second operation.
 * Preparation prevents native start until the original journal's cancellation
 * signal arrives. Repeating preparation for the same invocation is idempotent.
 */
export type PendingCancellation = { binding: ProviderBinding, operation_id: OperationId, };
