// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TestProjectId } from "./TestProjectId.js";

export type PluginTestProjectArguments = { id: TestProjectId, };
