// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BranchId } from "./BranchId.js";
import type { PluginBranch } from "./PluginBranch.js";

export type PluginBranchPage = { branches: Array<PluginBranch>, next: BranchId | null, };
