// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WindowId } from "./WindowId.js";

export type PluginWindowArguments = { window: WindowId, };
