// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BranchId } from "./BranchId.js";
import type { PluginId } from "./PluginId.js";
import type { RevisionId } from "./RevisionId.js";

export type PluginBranch = { id: BranchId, plugin: PluginId, name: string, head: RevisionId,
/**
 * The recorded branch point. Absent when no origin was recorded; never inferred.
 */
origin: RevisionId | null, };
