// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackageFile } from "./PackageFile.js";
import type { PackagePath } from "./PackagePath.js";
import type { RevisionId } from "./RevisionId.js";

export type PluginSourceChunk = { revision: RevisionId, path: PackagePath, file: PackageFile, offset: number,
/**
 * Binary-safe bytes. The owner verifies the full stored file digest before returning.
 */
content_base64: string, next_offset: number | null, };
