// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Native connection presence is an observation, not browser responsiveness or
 * authority to act. Closing remains distinct because a refused close can reopen.
 */
export type PluginViewPresenceState = "attached" | "closing" | "detached" | "closed";
