// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactId } from "./ArtifactId.js";
import type { PluginId } from "./PluginId.js";
import type { RevisionId } from "./RevisionId.js";

export type PluginCatalogItem = { revision: RevisionId, plugin: PluginId, name: string, version: string, description: string, artifacts: Array<ArtifactId>,
/**
 * Counts protectors without exposing another principal's operation identities.
 */
reference_count: number, };
