// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationId } from "./OperationId.js";
import type { RequestId } from "./RequestId.js";

/**
 * Observe a backend's original reverse Operation call. Identity is resolved
 * from the native caller and retained parent admission, never a caller selector.
 */
export type PluginDelegatedOperationArguments = { parent_operation: OperationId, request: RequestId, };
