// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginViewCloseState } from "./PluginViewCloseState.js";
import type { ViewInstanceId } from "./ViewInstanceId.js";

export type PluginViewLifecycle = { view: ViewInstanceId, close: PluginViewCloseState, };
