// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CapabilityKey } from "./CapabilityKey.js";
import type { OperationId } from "./OperationId.js";
import type { PluginArchiveReference } from "./PluginArchiveReference.js";
import type { RequestId } from "./RequestId.js";
import type { ResourceReference } from "./ResourceReference.js";
import type { JsonValue } from "./serde_json/JsonValue.js";

/**
 * Every request crosses the containing shell's scoped Host port. No browser
 * credential, project root or user identity is accepted from the iframe.
 */
export type PluginViewRequest = { "type": "register_close_handler", renderer: RequestId, } | { "type": "observe_lifecycle", renderer: RequestId, } | { "type": "prepare_close", renderer: RequestId, operation: OperationId, } | { "type": "refuse_close", renderer: RequestId, operation: OperationId, reason: string, } | { "type": "begin_text_copy" } | { "type": "finish_text_copy", copy_id: RequestId, text: string, } | { "type": "cancel_text_copy", copy_id: RequestId, } | { "type": "open_external_url", url: string, } | { "type": "download_resource", reference: ResourceReference, filename: string, } | { "type": "download_archive", reference: PluginArchiveReference, filename: string, } | { "type": "control", capability: CapabilityKey, arguments: JsonValue, } | { "type": "query", capability: CapabilityKey, arguments: JsonValue, } | { "type": "invoke", request_id: RequestId, capability: CapabilityKey, arguments: JsonValue, preconditions: Array<JsonValue>, } | { "type": "get_operation", operation_id: string, } | { "type": "cancel", operation_id: string, };
