// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderBinding } from "./ProviderBinding.js";
import type { JsonValue } from "./serde_json/JsonValue.js";

/**
 * Public Host payload: provider selection is separate from scientific arguments.
 */
export type PluginRequest = { binding: ProviderBinding, arguments: JsonValue, preconditions: JsonValue, };
