// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginInstance } from "./PluginInstance.js";

export type PluginInstanceObservation = { instance: PluginInstance,
/**
 * Whether this Host owns the observation. Inspect state separately; a stored
 * PID, failed instance or historical record is not evidence of a live process.
 */
observed_in_this_host: boolean, process_id: number | null, retained_calls: number | null, pending_messages: number | null, stderr: string | null, };
