// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationId } from "./OperationId.js";

export type PluginViewCloseState = { "phase": "open" } | { "phase": "requested", operation: OperationId, } | { "phase": "prepared", operation: OperationId, } | { "phase": "refused", operation: OperationId, reason: string, };
