// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginViewOrigin } from "./PluginViewOrigin.js";

/**
 * `None` means the admitted caller was not a view. A captured view that is no
 * longer present fails the observation rather than becoming a non-view caller.
 */
export type PluginViewCaller = { view: PluginViewOrigin | null, };
