// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PluginViewCloseMode = { "kind": "flush" } | { "kind": "retain_acknowledged", expected_version: number, };
