// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackageFile } from "./PackageFile.js";
import type { PackagePath } from "./PackagePath.js";
import type { RevisionId } from "./RevisionId.js";

export type PluginSourcePage = { revision: RevisionId, files: { [key in PackagePath]: PackageFile }, total: number, next: PackagePath | null, };
