// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectionId } from "./ConnectionId.js";
import type { PluginViewRequest } from "./PluginViewRequest.js";
import type { RequestId } from "./RequestId.js";
import type { ViewInstanceId } from "./ViewInstanceId.js";

export type PluginViewMessage = { protocol_version: number, connection: ConnectionId, view: ViewInstanceId, sequence: number, request: RequestId, body: PluginViewRequest, };
