// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackageFile } from "./PackageFile.js";
import type { PackagePath } from "./PackagePath.js";
import type { PluginManifest } from "./PluginManifest.js";
import type { RevisionId } from "./RevisionId.js";

export type PluginRevision = { id: RevisionId, parent: RevisionId | null, manifest: PluginManifest,
/**
 * Includes plugin.json, declarations, lockfiles and all first-party source.
 */
files: { [key in PackagePath]: PackageFile }, };
