// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectionId } from "./ConnectionId.js";
import type { ViewInstanceId } from "./ViewInstanceId.js";
import type { WindowId } from "./WindowId.js";

/**
 * Host-observed calling view identity. This contains no bridge or asset token
 * and cannot be presented as a credential for another call.
 */
export type PluginViewOrigin = { view: ViewInstanceId, window: WindowId, connection: ConnectionId, };
