// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginArchiveReference } from "./PluginArchiveReference.js";

export type PluginArchiveProgress = { reference: PluginArchiveReference, received: number,
/**
 * All ranges are staged. This alone is not package validation or import.
 */
complete: boolean, };
