// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginInstance } from "./PluginInstance.js";
import type { PluginInstanceId } from "./PluginInstanceId.js";

export type PluginInstancePage = { instances: Array<PluginInstance>, next: PluginInstanceId | null, total: number, };
