// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackagePath } from "./PackagePath.js";
import type { RevisionId } from "./RevisionId.js";

export type PluginSourceEdit = { "kind": "put", content_base64: string, executable: boolean, } | { "kind": "remove" } | { "kind": "copy", revision: RevisionId, path: PackagePath, };
