// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CapabilityRequirement } from "./CapabilityRequirement.js";
import type { ConnectionId } from "./ConnectionId.js";
import type { PackagePath } from "./PackagePath.js";
import type { PluginViewRecord } from "./PluginViewRecord.js";

export type PluginViewConnection = { view: PluginViewRecord, connection: ConnectionId, next_sequence: number,
/**
 * Short-lived asset authority for this view's exact immutable artifact only.
 */
asset_token: string,
/**
 * Retained by the containing shell. Never sent to the iframe or stored in
 * Operation records, scenarios, view state or source packages.
 */
call_token: string, entrypoint: PackagePath, grants: Array<CapabilityRequirement>, };
