// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackendEntrypoint } from "./BackendEntrypoint.js";
import type { CapabilityContribution } from "./CapabilityContribution.js";
import type { CapabilityRequirement } from "./CapabilityRequirement.js";
import type { ContextContribution } from "./ContextContribution.js";
import type { InstanceAlias } from "./InstanceAlias.js";
import type { PluginDependency } from "./PluginDependency.js";
import type { PluginId } from "./PluginId.js";
import type { SourceDeclaration } from "./SourceDeclaration.js";
import type { ViewContribution } from "./ViewContribution.js";
import type { JsonValue } from "./serde_json/JsonValue.js";

export type PluginManifest = { protocol_version: number, id: PluginId, name: string,
/**
 * Human-readable only. All bindings use revision and artifact digests.
 */
version: string, description: string, license: string, source: SourceDeclaration, dependencies: { [key in InstanceAlias]: PluginDependency }, requires: Array<CapabilityRequirement>,
/**
 * Available only when explicitly selected by the activation request.
 */
optional_requires?: Array<CapabilityRequirement>, views: Array<ViewContribution>, capabilities: Array<CapabilityContribution>, contexts: Array<ContextContribution>, backend: BackendEntrypoint | null, configuration_schema: JsonValue, default_configuration: JsonValue, };
