// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreatePluginTestProject } from "./CreatePluginTestProject.js";
import type { InstanceAlias } from "./InstanceAlias.js";
import type { InstanceRef } from "./InstanceRef.js";
import type { OperationId } from "./OperationId.js";
import type { PluginTestProjectState } from "./PluginTestProjectState.js";
import type { PrincipalId } from "./PrincipalId.js";
import type { ProjectId } from "./ProjectId.js";
import type { TestProjectId } from "./TestProjectId.js";

/**
 * Historical lifecycle metadata. Ready alone never proves a prior Host or
 * backend still exists; use the observation's explicit native-presence flag.
 */
export type PluginTestProject = { id: TestProjectId, source_project: ProjectId, principal: PrincipalId, source_operation_id: OperationId, project: ProjectId, directory: string, selection: CreatePluginTestProject, version: number, state: PluginTestProjectState, instances: { [key in InstanceAlias]: InstanceRef }, activation_operations: { [key in InstanceAlias]: OperationId }, diagnostic: string | null, };
