// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CapabilityKey } from "./CapabilityKey.js";
import type { JsonValue } from "./serde_json/JsonValue.js";

/**
 * An exact query fixture, never a backend reply or scientific evidence. Missing
 * arguments do not fall through to the real Host, even for read-only queries.
 */
export type PluginPreviewQuery = { capability: CapabilityKey, arguments: JsonValue, data: JsonValue, };
