// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginWindowNode } from "./PluginWindowNode.js";
import type { PrincipalId } from "./PrincipalId.js";
import type { ProjectId } from "./ProjectId.js";
import type { WindowId } from "./WindowId.js";

export type PluginWindowLayout = { window: WindowId, project: ProjectId, principal: PrincipalId,
/**
 * Changes only when this window's presentation is explicitly saved.
 */
version: number, layout: PluginWindowNode, };
