// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContributionId } from "./ContributionId.js";
import type { InstanceRef } from "./InstanceRef.js";
import type { PrincipalId } from "./PrincipalId.js";
import type { ProjectId } from "./ProjectId.js";
import type { ResourceReference } from "./ResourceReference.js";
import type { ViewInstanceId } from "./ViewInstanceId.js";
import type { WindowId } from "./WindowId.js";
import type { JsonValue } from "./serde_json/JsonValue.js";

export type PluginViewRecord = { view: ViewInstanceId, instance: InstanceRef, project: ProjectId, principal: PrincipalId, contribution: ContributionId, window: WindowId, configuration: JsonValue, state: JsonValue, resource?: ResourceReference, state_version: number, closed: boolean, };
