// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CapabilityKey } from "./CapabilityKey.js";
import type { InstanceRef } from "./InstanceRef.js";

export type PluginResolveArguments = { capability: CapabilityKey, instance: InstanceRef | null, target: string | null, };
