// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectionId } from "./ConnectionId.js";

export type PluginViewCloseMode = { "kind": "cooperate" } | { "kind": "disconnect", connection: ConnectionId | null, };
