// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginArchiveReference } from "./PluginArchiveReference.js";

/**
 * Explicit transient-byte cleanup. Receipts, revisions and artifacts are retained.
 */
export type PluginArchiveDiscarded = { reference: PluginArchiveReference, discarded: boolean, };
