// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArchiveId } from "./ArchiveId.js";
import type { ContentDigest } from "./ContentDigest.js";

export type PluginArchiveReference = { archive: ArchiveId, digest: ContentDigest, bytes: number, };
