// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginInstanceId } from "./PluginInstanceId.js";
import type { PluginInstanceObservation } from "./PluginInstanceObservation.js";

export type PluginInstanceObservations = { instances: Array<PluginInstanceObservation>, next: PluginInstanceId | null, total: number, };
