// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginInstanceId } from "./PluginInstanceId.js";

export type PluginInstancesArguments = { after: PluginInstanceId | null, limit: number,
/**
 * Runtime discovery excludes fixture previews unless explicitly requested.
 */
include_previews?: boolean, };
