// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginOutcome } from "./PluginOutcome.js";
import type { ProposedFact } from "./ProposedFact.js";
import type { ResourceReference } from "./ResourceReference.js";
import type { JsonValue } from "./serde_json/JsonValue.js";

export type PluginCommitPlan = { outcome: PluginOutcome, output: JsonValue | null, error: string | null, recovery: JsonValue | null, facts: Array<ProposedFact>, evidence: Array<ResourceReference>,
/**
 * True only after the owner has confirmed execution stopped.
 */
cancellation_confirmed: boolean, };
