// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationId } from "./OperationId.js";
import type { TestProjectId } from "./TestProjectId.js";

export type PluginTestOperationArguments = { id: TestProjectId, operation_id: OperationId, };
