// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginArchiveReference } from "./PluginArchiveReference.js";
import type { PluginArtifactSummary } from "./PluginArtifactSummary.js";
import type { PluginId } from "./PluginId.js";
import type { RevisionId } from "./RevisionId.js";

export type PluginArchiveInspection = { reference: PluginArchiveReference, revision: RevisionId, plugin: PluginId, name: string, version: string, description: string, source_files: number, artifacts: Array<PluginArtifactSummary>, };
