// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginInstanceId } from "./PluginInstanceId.js";

export type PluginInstancesArguments = { after: PluginInstanceId | null, limit: number, };
