// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginTestProject } from "./PluginTestProject.js";

export type PluginTestProjectObservation = { project: PluginTestProject, observed_in_this_host: boolean, };
