// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BranchId } from "./BranchId.js";
import type { RevisionId } from "./RevisionId.js";

export type PluginCheckpoint = { branch: BranchId, revision: RevisionId, parent: RevisionId, };
