// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstanceRef } from "./InstanceRef.js";
import type { PluginViewPresenceState } from "./PluginViewPresenceState.js";
import type { ViewInstanceId } from "./ViewInstanceId.js";
import type { WindowId } from "./WindowId.js";

export type PluginViewPresence = { view: ViewInstanceId, window: WindowId, instance: InstanceRef, state: PluginViewPresenceState, };
