// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginTestProjectObservation } from "./PluginTestProjectObservation.js";
import type { TestProjectId } from "./TestProjectId.js";

export type PluginTestProjectPage = { projects: Array<PluginTestProjectObservation>, next: TestProjectId | null, };
