// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginCatalogItem } from "./PluginCatalogItem.js";
import type { RevisionId } from "./RevisionId.js";

export type PluginCatalogPage = { items: Array<PluginCatalogItem>, next: RevisionId | null, total: number, };
