// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildArtifact } from "./BuildArtifact.js";
import type { ContentDigest } from "./ContentDigest.js";
import type { PluginRevision } from "./PluginRevision.js";

/**
 * A bounded, versioned local archive. Content-addressed blobs avoid duplicate bytes.
 * JSON plus base64 makes the import format independent of native archive extractors.
 */
export type PluginArchive = { format_version: number, revision: PluginRevision, artifacts: Array<BuildArtifact>, blobs: { [key in ContentDigest]: string }, };
