// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationId } from "./OperationId.js";

export type PluginDelegatedOperation = {
/**
 * Null means no visible durable record was observed. It does not prove
 * that dispatch did not happen and must never authorize a replay.
 */
operation_id: OperationId | null, };
