// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactId } from "./ArtifactId.js";
import type { OperationId } from "./OperationId.js";
import type { ProcessReport } from "./ProcessReport.js";
import type { RevisionId } from "./RevisionId.js";

export type PluginBuildResult = { operation_id: OperationId, revision: RevisionId, artifact: ArtifactId | null,
/**
 * Bounded native evidence, not an independent Operation outcome.
 */
process: ProcessReport, diagnostic: string | null, };
