// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactId } from "./ArtifactId.js";
import type { PluginArchiveReference } from "./PluginArchiveReference.js";
import type { PluginId } from "./PluginId.js";
import type { RevisionId } from "./RevisionId.js";

export type PluginArchiveReceipt = { reference: PluginArchiveReference, revision: RevisionId, plugin: PluginId, artifacts: Array<ArtifactId>, };
