// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstalledPluginRevision } from "./InstalledPluginRevision.js";
import type { RevisionId } from "./RevisionId.js";

export type PluginRevisionPage = { revisions: Array<InstalledPluginRevision>, next: RevisionId | null, total: number, };
