// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RequestId } from "./RequestId.js";
import type { ViewInstanceId } from "./ViewInstanceId.js";

export type PluginViewRendererRelease = { view: ViewInstanceId, renderer: RequestId,
/**
 * False on an identical repeat. This acknowledges only deregistration,
 * never saved content, view closure or backend release.
 */
released: boolean, };
