// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContextReference } from "./ContextReference.js";
import type { JsonValue } from "./serde_json/JsonValue.js";

export type PreviewContext = { reference: ContextReference,
/**
 * Owner-defined inclusion, such as a captured selection or a table range.
 */
inclusion: JsonValue, max_bytes: number, };
