// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactId } from "./ArtifactId.js";
import type { InstanceAlias } from "./InstanceAlias.js";
import type { PluginPreviewQuery } from "./PluginPreviewQuery.js";
import type { RevisionId } from "./RevisionId.js";
import type { JsonValue } from "./serde_json/JsonValue.js";

/**
 * Create a disposable presentation instance of an existing immutable artifact.
 * It has no backend, Host grants, provider registrations or project data path.
 * Open/close its views and release it through the ordinary lifecycle ports.
 */
export type PreviewPlugin = { revision: RevisionId, artifact: ArtifactId, alias: InstanceAlias, configuration: JsonValue, queries: Array<PluginPreviewQuery>, };
