// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OutputCapture } from "./OutputCapture.js";
import type { ProcessTermination } from "./ProcessTermination.js";

export type ProcessReport = { pid: number | null, exit_code: number | null, exit_signal: number | null, termination: ProcessTermination, stdout: OutputCapture, stderr: OutputCapture, elapsed_ms: number, supervision: string, stdin_error: string | null, cleanup_requested: boolean, cleanup_error: string | null, };
