// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Current metadata coverage, not a lease or a claim that materials are unused.
 * Requires project.references.read in addition to the owner's normal read scope.
 * No foreign identities, counts, configuration or scientific data are disclosed.
 */
export type ProjectReadCoverage = { all_visible: boolean, };
