// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CapabilityKey } from "./CapabilityKey.js";
import type { InstanceRef } from "./InstanceRef.js";
import type { ProjectId } from "./ProjectId.js";

export type ProviderBinding = { capability: CapabilityKey, provider: InstanceRef, project: ProjectId,
/**
 * Owner-defined native identity, fixed at admission. Not interpreted by core.
 */
target: string | null, };
