// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginArchiveReference } from "./PluginArchiveReference.js";

export type ReadPluginArchive = { reference: PluginArchiveReference, offset: number, limit: number, };
