// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DraftId } from "./DraftId.js";
import type { WindowId } from "./WindowId.js";

export type ReadDocumentDraft = { window: WindowId, draft: DraftId, expected_version: number, offset: number, limit: number, };
