// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ViewInstanceId } from "./ViewInstanceId.js";

/**
 * Reattach the retained view of an already active instance without creating a
 * new view identity or replaying an earlier invocation.
 */
export type ReconnectPluginView = { view: ViewInstanceId, };
