// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectionId } from "./ConnectionId.js";
import type { RequestId } from "./RequestId.js";
import type { ViewInstanceId } from "./ViewInstanceId.js";
import type { WindowId } from "./WindowId.js";

/**
 * Sent by the containing shell after this exact document is destroyed. The
 * private credential must never enter a plugin frame or an Operation journal.
 */
export type ReleasePluginViewRenderer = { view: ViewInstanceId, connection: ConnectionId, window: WindowId, renderer: RequestId, call_token: string, };
