// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RequestId } from "./RequestId.js";
import type { ResourceTransfer } from "./ResourceTransfer.js";

export type ResourceTransferRequest = { version: number, token: string, parent_request: RequestId, transfer: ResourceTransfer, };
