// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResourceReference } from "./ResourceReference.js";

export type ResourceTransferResponse = { "type": "stored", "data": ResourceReference } | { "type": "data", "data": { reference: ResourceReference, offset: number, bytes: number, next: number | null, } } | { "type": "error", "data": { message: string, } };
