// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResourceDeclaration } from "./ResourceDeclaration.js";
import type { ResourceRead } from "./ResourceRead.js";

export type ResourceTransfer = { "type": "put", "data": ResourceDeclaration } | { "type": "read", "data": ResourceRead };
