// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An ephemeral, instance-only data transport. Never a general Host credential.
 * Connect once per transfer; send a BE u32 JSON length, the header, then raw
 * upload bytes, and close the write half. Responses use the same header framing.
 */
export type ResourceChannel = { version: number, socket: string, token: string, };
