// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResourceReference } from "./ResourceReference.js";

export type ResourceChunk = { reference: ResourceReference, offset: number, base64: string, next: number | null, };
