// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstanceRef } from "./InstanceRef.js";
import type { ResourceId } from "./ResourceId.js";

export type ResourceList = { owner: InstanceRef | null, after: ResourceId | null, limit: number, };
