// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentDigest } from "./ContentDigest.js";
import type { InstanceRef } from "./InstanceRef.js";
import type { ResourceId } from "./ResourceId.js";

export type ResourceReference = { owner: InstanceRef, resource: ResourceId, digest: ContentDigest, media_type: string, bytes: number, };
