// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResourceId } from "./ResourceId.js";
import type { ResourceReference } from "./ResourceReference.js";

export type ResourcePage = { items: Array<ResourceReference>, next: ResourceId | null, total: number, };
