// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstanceRef } from "./InstanceRef.js";
import type { RequestId } from "./RequestId.js";

/**
 * Resume one confirmed Host suspension. Configuration and grants are retained
 * by the Host; the caller cannot replace them through recovery.
 */
export type ResumePlugin = { instance: InstanceRef, suspension: RequestId, };
