// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RevisionId } from "./RevisionId.js";
import type { SourceFileDifference } from "./SourceFileDifference.js";

export type RevisionDifference = { before: RevisionId, after: RevisionId, files: Array<SourceFileDifference>, };
