// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactId } from "./ArtifactId.js";
import type { BackendEnvironment } from "./BackendEnvironment.js";
import type { CapabilityKey } from "./CapabilityKey.js";
import type { CapabilityRequirement } from "./CapabilityRequirement.js";
import type { ObservationCompleteness } from "./ObservationCompleteness.js";
import type { OperationSettlement } from "./OperationSettlement.js";
import type { PendingCancellation } from "./PendingCancellation.js";
import type { PluginCall } from "./PluginCall.js";
import type { PluginCommitPlan } from "./PluginCommitPlan.js";
import type { PluginInstance } from "./PluginInstance.js";
import type { RequestId } from "./RequestId.js";
import type { ResourceChannel } from "./ResourceChannel.js";
import type { ResourceReference } from "./ResourceReference.js";
import type { RevisionId } from "./RevisionId.js";
import type { JsonValue } from "./serde_json/JsonValue.js";

export type RpcBody = { "type": "initialize", "data": { instance: PluginInstance, grants: Array<CapabilityRequirement>, environment?: BackendEnvironment | null, resource_channel?: ResourceChannel | null, } } | { "type": "ready", "data": { revision: RevisionId, artifact: ArtifactId,
/**
 * Optional protocol extensions. Unknown bounded names are ignored by
 * Hosts; an extension is used only after exact readiness advertises it.
 */
features?: Array<string>, } } | { "type": "query", "data": PluginCall } | { "type": "control", "data": PluginCall } | { "type": "invoke", "data": PluginCall } | { "type": "query_result", "data": { data: JsonValue, completeness: ObservationCompleteness, source: ResourceReference | null,
/**
 * Owner-reported Unix milliseconds when this data was observed, not
 * when the reply was sent. Cached reads retain the original time.
 * Omitted or null means unknown; the Host must not invent a timestamp.
 */
observed_at_ms: number | null,
/**
 * Owner limitations on this observation, preserved in the public
 * query envelope. Subject to the existing control/response byte bound.
 */
notices: Array<string>, } } | { "type": "control_result", "data": { data: JsonValue, } } | { "type": "commit_plan", "data": PluginCommitPlan } | { "type": "host_call", "data": {
/**
 * Active incoming call whose authority this reverse call inherits.
 */
parent_request: RequestId, capability: CapabilityKey, arguments: JsonValue, } } | { "type": "host_result", "data": { result: JsonValue, } } | { "type": "cancel", "data": { operation_id: string, } } | { "type": "cancel_acknowledged", "data": { operation_id: string, confirmed: boolean, } } | { "type": "prepare_pending_cancellation", "data": PendingCancellation } | { "type": "pending_cancellation_prepared", "data": { cancellation: PendingCancellation, prepared: boolean, } } | { "type": "operation_settled", "data": OperationSettlement } | { "type": "settlement_acknowledged", "data": OperationSettlement } | { "type": "release" } | { "type": "released" } | { "type": "error", "data": { code: string, message: string, recovery: JsonValue | null, } };
