// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectionId } from "./ConnectionId.js";
import type { PluginInstanceId } from "./PluginInstanceId.js";
import type { RequestId } from "./RequestId.js";
import type { RpcBody } from "./RpcBody.js";

/**
 * Each direction has its own strictly increasing sequence starting at one.
 * Connection identity is host-issued and rotated for every transport incarnation.
 */
export type RpcFrame = { protocol_version: number, connection: ConnectionId, instance: PluginInstanceId, sequence: number, request: RequestId, body: RpcBody, };
