// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstanceAlias } from "./InstanceAlias.js";
import type { ScenarioId } from "./ScenarioId.js";
import type { ScenarioInstance } from "./ScenarioInstance.js";
import type { ScenarioLayout } from "./ScenarioLayout.js";
import type { ScenarioProvider } from "./ScenarioProvider.js";
import type { ScenarioRevisionId } from "./ScenarioRevisionId.js";

/**
 * Save an immutable checkpoint and compare-and-swap this named scenario's head.
 * Project and principal are supplied by the Host, never by the request.
 */
export type SaveScenario = { scenario: ScenarioId, expected_head: ScenarioRevisionId | null, name: string, instances: { [key in InstanceAlias]: ScenarioInstance }, providers: Array<ScenarioProvider>, layout: ScenarioLayout, };
