// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DraftContent } from "./DraftContent.js";
import type { DraftId } from "./DraftId.js";
import type { DraftSource } from "./DraftSource.js";
import type { RequestId } from "./RequestId.js";
import type { WindowId } from "./WindowId.js";
import type { JsonValue } from "./serde_json/JsonValue.js";

export type SaveDocumentDraft = { window: WindowId, draft: DraftId, upload: RequestId, source: DraftSource,
/**
 * None creates a new identity; Some updates only that existing version.
 */
expected_version: number | null, content: DraftContent, metadata: JsonValue, };
