// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScenarioId } from "./ScenarioId.js";
import type { ScenarioSummary } from "./ScenarioSummary.js";

export type ScenarioPage = { scenarios: Array<ScenarioSummary>, next: ScenarioId | null, };
