// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CapabilityKey } from "./CapabilityKey.js";
import type { InstanceAlias } from "./InstanceAlias.js";

export type ScenarioProvider = { capability: CapabilityKey, instance: InstanceAlias, target: string | null, };
