// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScenarioId } from "./ScenarioId.js";
import type { ScenarioRevisionId } from "./ScenarioRevisionId.js";

export type ScenarioSummary = { scenario: ScenarioId, revision: ScenarioRevisionId, name: string, };
