// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstanceAlias } from "./InstanceAlias.js";
import type { ProjectId } from "./ProjectId.js";
import type { ScenarioId } from "./ScenarioId.js";
import type { ScenarioInstance } from "./ScenarioInstance.js";
import type { ScenarioLayout } from "./ScenarioLayout.js";
import type { ScenarioProvider } from "./ScenarioProvider.js";
import type { ScenarioRevisionId } from "./ScenarioRevisionId.js";

export type ScenarioRevision = { id: ScenarioRevisionId, parent: ScenarioRevisionId | null, scenario: ScenarioId, project: ProjectId, name: string, instances: { [key in InstanceAlias]: ScenarioInstance }, providers: Array<ScenarioProvider>, layout: ScenarioLayout, };
