// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContributionId } from "./ContributionId.js";
import type { InstanceAlias } from "./InstanceAlias.js";
import type { ResourceReference } from "./ResourceReference.js";
import type { RevisionId } from "./RevisionId.js";
import type { ViewInstanceId } from "./ViewInstanceId.js";
import type { JsonValue } from "./serde_json/JsonValue.js";

export type ScenarioView = { id: ViewInstanceId, instance: InstanceAlias, contribution: ContributionId, configuration: JsonValue, state: JsonValue,
/**
 * State is only opened under the exact revision that authored its schema.
 */
state_revision: RevisionId, resource: ResourceReference | null, };
