// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeId } from "./NodeId.js";
import type { ScenarioView } from "./ScenarioView.js";
import type { SplitDirection } from "./SplitDirection.js";
import type { ViewInstanceId } from "./ViewInstanceId.js";

export type ScenarioLayout = { "kind": "empty" } | { "kind": "split", id: NodeId, direction: SplitDirection, weights: Array<number>, children: Array<ScenarioLayout>, } | { "kind": "tabs", id: NodeId, selected: ViewInstanceId | null, views: Array<ScenarioView>, };
