// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildRecipe } from "./BuildRecipe.js";
import type { PackagePath } from "./PackagePath.js";

export type SourceDeclaration = {
/**
 * Every first-party source file must be included in the package snapshot.
 */
files: Array<PackagePath>, lockfiles: Array<PackagePath>, build_instructions: PackagePath,
/**
 * Executed only by an explicit development build, never by import or query.
 */
build: BuildRecipe | null, };
