// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackageFile } from "./PackageFile.js";
import type { PackagePath } from "./PackagePath.js";

export type SourceFileDifference = { path: PackagePath, before: PackageFile | null, after: PackageFile | null, };
