// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentDigest } from "./ContentDigest.js";
import type { DraftId } from "./DraftId.js";
import type { RequestId } from "./RequestId.js";
import type { WindowId } from "./WindowId.js";

export type StageDraftChunk = { window: WindowId, draft: DraftId,
/**
 * One captured save attempt. Concurrent captures retain separate staging
 * leases even when their byte chunks are identical.
 */
upload: RequestId, digest: ContentDigest, base64: string, };
