// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginArchiveReference } from "./PluginArchiveReference.js";

export type StagePluginArchive = { reference: PluginArchiveReference, offset: number, base64: string, };
