// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginWindowNode } from "./PluginWindowNode.js";
import type { WindowId } from "./WindowId.js";

export type UpdatePluginWindowLayout = { window: WindowId, expected_version: number, layout: PluginWindowNode, };
