// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ViewInstanceId } from "./ViewInstanceId.js";
import type { JsonValue } from "./serde_json/JsonValue.js";

export type UpdatePluginView = { view: ViewInstanceId,
/**
 * An owner-specific state version, never a global scientific revision.
 */
expected_version: number, state: JsonValue, };
