// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContributionId } from "./ContributionId.js";
import type { PackagePath } from "./PackagePath.js";
import type { JsonValue } from "./serde_json/JsonValue.js";

export type ViewContribution = { id: ContributionId, title: string, entrypoint: PackagePath, configuration_schema: JsonValue, resource_kinds: Array<string>, };
