// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContributionId } from "./ContributionId.js";
import type { CustomComponent } from "./CustomComponent.js";
import type { NodeId } from "./NodeId.js";
import type { VisualDataSource } from "./VisualDataSource.js";
import type { VisualNode } from "./VisualNode.js";

/**
 * Both the canvas and declaration editor modify this model. Custom source is
 * referenced by path; it is never reconstructed from a rendered component.
 */
export type VisualDocument = { format_version: number, root: NodeId, nodes: { [key in NodeId]: VisualNode }, data_sources: { [key in ContributionId]: VisualDataSource }, components: { [key in ContributionId]: CustomComponent }, };
