// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DataBinding } from "./DataBinding.js";
import type { JsonValue } from "./serde_json/JsonValue.js";

export type VisualCondition = { "kind": "exists", binding: DataBinding, } | { "kind": "equals", binding: DataBinding, value: JsonValue, } | { "kind": "not", condition: VisualCondition, } | { "kind": "all", conditions: Array<VisualCondition>, };
