// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContributionId } from "./ContributionId.js";
import type { DataBinding } from "./DataBinding.js";
import type { NodeId } from "./NodeId.js";
import type { VisualAction } from "./VisualAction.js";
import type { VisualCondition } from "./VisualCondition.js";
import type { VisualNodeKind } from "./VisualNodeKind.js";
import type { JsonValue } from "./serde_json/JsonValue.js";

export type VisualNode = { kind: VisualNodeKind, children: Array<NodeId>, properties: { [key in string]: JsonValue }, style_tokens: { [key in string]: string }, bindings: { [key in string]: DataBinding }, visible_when: VisualCondition | null, events: { [key in string]: Array<VisualAction> }, component: ContributionId | null, };
