// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CapabilityKey } from "./CapabilityKey.js";
import type { ContributionId } from "./ContributionId.js";
import type { DataBinding } from "./DataBinding.js";
import type { JsonValue } from "./serde_json/JsonValue.js";

export type VisualAction = { "kind": "invoke", capability: CapabilityKey, arguments: JsonValue, } | { "kind": "open_view", contribution: ContributionId, resource: DataBinding | null, } | { "kind": "set_state", key: string, value: JsonValue, } | { "kind": "refresh", source: ContributionId, };
