// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginWindowLayout } from "./PluginWindowLayout.js";
import type { WindowScenario } from "./WindowScenario.js";

export type WindowScenarioSnapshot = { scenario: WindowScenario | null, layout: PluginWindowLayout, };
