// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstanceAlias } from "./InstanceAlias.js";
import type { InstanceRef } from "./InstanceRef.js";
import type { PrincipalId } from "./PrincipalId.js";
import type { ProjectId } from "./ProjectId.js";
import type { ProviderBinding } from "./ProviderBinding.js";
import type { ScenarioRevisionId } from "./ScenarioRevisionId.js";
import type { ViewInstanceId } from "./ViewInstanceId.js";
import type { WindowId } from "./WindowId.js";

export type WindowScenario = { window: WindowId, project: ProjectId, principal: PrincipalId, revision: ScenarioRevisionId,
/**
 * Native layout version at application; later docking edits can advance it.
 */
applied_layout_version: number, instances: { [key in InstanceAlias]: InstanceRef }, views: { [key in ViewInstanceId]: ViewInstanceId }, providers: Array<ProviderBinding>, };
