// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Host-owned path boundaries, obtained through the scoped `workspace.paths`
 * query. They are metadata, not a filesystem sandbox or a caller configuration.
 * Both existing and future paths are included; consumers must preserve lexical
 * and resolved exclusions when exposing filesystem capabilities.
 */
export type WorkspacePaths = { project_root: string, protected_paths: Array<string>, };
